spring:
  application:
    name: eureka-client-producer
server:
  port: 2001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/
  registry-fetch-interval-seconds: 60
  instance:
    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


# 健康检查
#eureka.client.healthcheck.enabled=true

# 随机端口配置
#eureka.instance.instance-id=${spring.application.name}:${random.int}
#server.port=0
#server.port=${random.int[10000,19999]}
