spring:
  application:
    name: eureka-client-consumer
server:
  port: 3001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/
  registry-fetch-interval-seconds: 60
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF