spring:
  application:
    name: eureka-client-consumer
server:
  port: 3001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF